### ISSUE TITLE
Two more Chrome error messages

### ISSUE THREAD

**Issue by azankl** [sepetab/Plugin_Biodata-HPO-#10]
Getting these new Chrome error messages now:

<img width="677" alt="Chrome-error" src="https://user-images.githubusercontent.com/4812335/91652021-914f0f80-ead6-11ea-86ec-88da1b0cc67f.png">

**Comment by anthonyaxu** [comment]
I have changed the link for the HPO Jax API so the second error message should be fixed now. 

Could you please let us know the steps of how the first error occurred (eg. website, how many terms stored in history at the time,  which terms were selected to be stored, etc).

**Comment by azankl** [comment]
The second error occurs when I click the Ontoclick icon in the toolbar, then type in a search term and then click the little disc icon to save the chosen term to history. This comes back to our initial problem that the 'save to history' function does not work properly when the extension is launched from the toolbar, rather than from a contextual menu. So the easy workaround would be to hide the disc icon when the extension is launched from the toolbar (like you already hide the history list icons because they did not work properly). The better option would be of course figuring out why the history function does not work properly when the extension is launched from the toolbar.

**Comment by anthonyaxu** [comment]
I have removed the little icon when accessing the popup from the toolbar. With how the code is currently written, it isn't possible to have a history/export feature when using the plugin from the toolbar. This is because the plugin bypasses some functions when activated from the toolbar.

**Comment by azankl** [comment]
That's OK, all working now. Thanks.
