### ISSUE TITLE
Ontoclick popup goes all jittery when I select HPO and Gene Ontology

### ISSUE THREAD

**Issue by azankl** [sepetab/Plugin_Biodata-HPO-#11]
When I open the Ontoclick window from the toolbar and then select both HPO and Gene Ontology from the dropdown menu, the Ontoclick Popup starts to jiggers frantically, looks like it's trying to resize the window and then keeps flicking back and forth between the two sizes. When I add another ontology to the list, it stops. It only seems to happen in this particular combination (HPO and GO). When I open the popup via the contextual menu and select HPO and GO, everything works normally.

**Comment by anthonyaxu** [comment]
I have changed it so that the size of the popup from the toolbar is fixed, instead of changing to the size of the text inside. I believe this issue should now be fixed.

**Comment by azankl** [comment]
works! Thanks!
