### ISSUE TITLE
'Refused to load script' error when using the extension

### ISSUE THREAD

**Issue by azankl** [sepetab/Plugin_Biodata-HPO-#8]
I build the extension with 'yarn run build' and loaded the unpacked extension into Chrome. Everything seems to work, but I discovered some 'Refused to load script' errors in the Chrome Extension Settings, see screenshot below:

<img width="679" alt="Chrome_error" src="https://user-images.githubusercontent.com/4812335/91554167-f2a99e00-e971-11ea-893d-2f400086b536.png">

**Comment by anthonyaxu** [comment]
I have made some changes to the content security policy in the manifest file. It should be displaying results now.

**Comment by azankl** [comment]
Dont get this error anymore. Fixed.
